require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/todo_models", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TodoModel. As you add validations to TodoModel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TodoModel.create! valid_attributes
      get todo_models_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      todo_model = TodoModel.create! valid_attributes
      get todo_model_url(todo_model)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_todo_model_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      todo_model = TodoModel.create! valid_attributes
      get edit_todo_model_url(todo_model)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TodoModel" do
        expect {
          post todo_models_url, params: { todo_model: valid_attributes }
        }.to change(TodoModel, :count).by(1)
      end

      it "redirects to the created todo_model" do
        post todo_models_url, params: { todo_model: valid_attributes }
        expect(response).to redirect_to(todo_model_url(TodoModel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TodoModel" do
        expect {
          post todo_models_url, params: { todo_model: invalid_attributes }
        }.to change(TodoModel, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post todo_models_url, params: { todo_model: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested todo_model" do
        todo_model = TodoModel.create! valid_attributes
        patch todo_model_url(todo_model), params: { todo_model: new_attributes }
        todo_model.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the todo_model" do
        todo_model = TodoModel.create! valid_attributes
        patch todo_model_url(todo_model), params: { todo_model: new_attributes }
        todo_model.reload
        expect(response).to redirect_to(todo_model_url(todo_model))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        todo_model = TodoModel.create! valid_attributes
        patch todo_model_url(todo_model), params: { todo_model: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested todo_model" do
      todo_model = TodoModel.create! valid_attributes
      expect {
        delete todo_model_url(todo_model)
      }.to change(TodoModel, :count).by(-1)
    end

    it "redirects to the todo_models list" do
      todo_model = TodoModel.create! valid_attributes
      delete todo_model_url(todo_model)
      expect(response).to redirect_to(todo_models_url)
    end
  end
end
